### ISSUE TITLE
Icon format

### ISSUE THREAD

**Issue by MohamadElhadidy** [zero-to-mastery/canvas-2022#111]
my icon is gif format 
it was added as png  Can you fix it 

` {
    "name": "Egyptian Flag",
    "page_link": "./art/MohamadElhadidy/index.html",
    "art_icon": "./art/MohamadElhadidy/icon.png", // icon.gif
    "author_name": "Mohamad Elhadidy",
    "author_github_url": "https://github.com/MohamadElhadidy"
  }`

**Comment by auxfuse** [comment]
Hi @MohamadElhadidy please don't open Issues for requests of this type.

You can resolve this yourself using a new branch, and following along to the contributor guidelines specifically.
https://github.com/zero-to-mastery/canvas-2022#%EF%B8%8F-how-to-contribute

Open a PR when you are ready to fix, we will review and merge to get it sorted for you. Thanks for understanding, we are going to close this out now. 🤜

**Comment by MohamadElhadidy** [comment]
Instructions in  the guidelines  said that i can't edit this file
The format is wrong in a file only you can update
