### ISSUE TITLE
I have updated my canvas art, open for someone to review.

### ISSUE THREAD

**Issue by avatar-10000** [zero-to-mastery/canvas-2022#48]
can someone review this pull request 😸 

[https://github.com/zero-to-mastery/canvas-2022/pull/24](https://github.com/zero-to-mastery/canvas-2022/pull/24)

**Comment by Anudeep-313** [comment]
this pr can be merged, everything seems fine!!

**Comment by auxfuse** [comment]
Please don't open Issues for PRs that are pending review. We are trying our best to get around to all PRs as they come in. You still have a question left unfulfilled on your PR. I'll make reference to it on my next review. We appreciate your patience.

This issue will be closed now. 🤜
